import test from "node:test";import assert from "node:assert/strict";
import {validatePlaybook,promptFor} from "../dist/intelligence/playbook.js";
import {evaluateAnswer,assertSafeGeneratedText} from "../dist/intelligence/safety.js";
import {MemoryIntelligenceStore} from "../dist/intelligence/memory-store.js";
import {BookingService} from "../dist/intelligence/booking.js";
import {IntelligenceEngine} from "../dist/intelligence/engine.js";
import {applianceRepairPlaybook,SERVICE_SAFETY_POLICY} from "../dist/intelligence/reference-playbooks.js";
const now="2026-07-14T08:00:00.000Z";
class Model{constructor(label="washing_machine",confidence=.9){this.label=label;this.confidence=confidence;}async classify(){return{label:this.label,confidence:this.confidence,rationaleCode:"bounded"};}}
class Provider{calls=[];async confirm(input){this.calls.push(input);return{providerBookingId:`book_${input.idempotencyKey}`};}async cancel(){} }

test("approved playbook validates and locale prompt resolves",()=>{const p=applianceRepairPlaybook("org",now);validatePlaybook(p);assert.match(promptFor(p,"ta","service"),/சாதன/);});
test("playbook cycles and unreachable nodes are rejected",()=>{const p=applianceRepairPlaybook("org",now);p.nodes.find(n=>n.id==="location").next="service";assert.throws(()=>validatePlaybook(p),/playbook_cycle/);});
test("emergency language forces handoff and prohibited fields reject",()=>{assert.equal(evaluateAnswer({...SERVICE_SAFETY_POLICY,organizationId:"org"},"symptom","there is a gas leak").action,"handoff");assert.equal(evaluateAnswer({...SERVICE_SAFETY_POLICY,organizationId:"org"},"card_number","4111").action,"reject");});
test("generated promises are blocked",()=>{assert.throws(()=>assertSafeGeneratedText({...SERVICE_SAFETY_POLICY,organizationId:"org"},"We guarantee an exact price"),/prohibited/);});
test("conversation pins approved version and follows deterministic branches",async()=>{const s=new MemoryIntelligenceStore();const p=applianceRepairPlaybook("org",now);await s.saveSafetyPolicy({...SERVICE_SAFETY_POLICY,organizationId:"org"});const e=new IntelligenceEngine(s,new Model(),()=>new Date(now));await e.register(p);let out=await e.start("org","lead","appliance_repair_v1","en");assert.equal(out.action,"ask");out=await e.answer("org",out.session.id,"washing machine leaking");assert.equal(out.session.answers.appliance,"washing_machine");assert.equal(out.session.currentNodeId,"symptom");});
test("low model confidence fails safe to human handoff",async()=>{const s=new MemoryIntelligenceStore();const p=applianceRepairPlaybook("org",now);await s.saveSafetyPolicy({...SERVICE_SAFETY_POLICY,organizationId:"org"});const e=new IntelligenceEngine(s,new Model("washing_machine",.4),()=>new Date(now));await e.register(p);const start=await e.start("org","lead","appliance_repair_v1","en");const out=await e.answer("org",start.session.id,"washer");assert.equal(out.action,"handoff");assert.ok(out.session.flags.includes("low_model_confidence"));});
test("emergency answer moves session to handoff",async()=>{const s=new MemoryIntelligenceStore();const p=applianceRepairPlaybook("org",now);await s.saveSafetyPolicy({...SERVICE_SAFETY_POLICY,organizationId:"org"});const e=new IntelligenceEngine(s,new Model(),()=>new Date(now));await e.register(p);const start=await e.start("org","lead","appliance_repair_v1","en");const out=await e.answer("org",start.session.id,"gas leak and fire");assert.equal(out.action,"handoff");});
test("slot capacity prevents double holds",async()=>{const s=new MemoryIntelligenceStore();await s.addSlot({id:"slot",organizationId:"org",resourceId:"tech",startsAt:"2026-07-15T10:00:00Z",endsAt:"2026-07-15T11:00:00Z",capacity:1});const b=new BookingService(s,new Provider(),()=>new Date(now));await b.hold("org","s1","slot");await assert.rejects(b.hold("org","s2","slot"),/slot_unavailable/);});
test("booking confirmation is idempotent",async()=>{const s=new MemoryIntelligenceStore();const provider=new Provider();await s.addSlot({id:"slot",organizationId:"org",resourceId:"tech",startsAt:"2026-07-15T10:00:00Z",endsAt:"2026-07-15T11:00:00Z",capacity:1});const b=new BookingService(s,provider,()=>new Date(now));const h=await b.hold("org","s1","slot");const a=await b.confirm("org",h.id);const again=await b.confirm("org",h.id);assert.equal(a.providerBookingId,again.providerBookingId);assert.equal(provider.calls.length,1);});
test("expired hold cannot confirm",async()=>{const s=new MemoryIntelligenceStore();const clock={value:new Date(now)};await s.addSlot({id:"slot",organizationId:"org",resourceId:"tech",startsAt:"2026-07-15T10:00:00Z",endsAt:"2026-07-15T11:00:00Z",capacity:1});const b=new BookingService(s,new Provider(),()=>new Date(clock.value));const h=await b.hold("org","s1","slot",30);clock.value=new Date(clock.value.getTime()+31000);await assert.rejects(b.confirm("org",h.id),/hold_expired/);});
