import test from "node:test";import assert from "node:assert/strict";
import {MemoryAttributionStore} from "../dist/attribution/memory-store.js";
import {appendEvidence,addAcquisitionTouch,linkIdentity} from "../dist/attribution/ledger.js";
import {AttributionEngine} from "../dist/attribution/engine.js";
import {aggregateCohort} from "../dist/attribution/cohort.js";
import {accrueCommission,requirePartnerScope,reverseCommission} from "../dist/attribution/partners.js";
import {CrmSyncService} from "../dist/attribution/crm.js";
const t="2026-07-14T10:00:00.000Z";
function event(id,kind,amountMinor,strength="financial_verified",confidence=1){const e={id,organizationId:"org",leadId:"lead",kind,occurredAt:t,sourceId:id,sourceType:"test",strength,confidence,ruleVersion:"recovery-v1",metadata:{}};if(amountMinor!==undefined){e.amountMinor=amountMinor;e.currency="INR";}return e;}

test("ledger deduplicates provider source events",async()=>{const s=new MemoryAttributionStore();assert.equal(await appendEvidence(s,event("p1","payment_collected",10000)),true);assert.equal(await appendEvidence(s,{...event("p2","payment_collected",10000),sourceId:"p1"}),false);});
test("financial events require verified strength, amount, and currency",async()=>{const s=new MemoryAttributionStore();await assert.rejects(appendEvidence(s,event("p","payment_collected",100,"owner_reported")),/financial_event/);await assert.rejects(appendEvidence(s,event("missing","payment_collected",undefined)),/amount_and_currency/);});
test("report separates value stages, evidence strength, attribution, refunds, and cost",async()=>{const s=new MemoryAttributionStore();for(const e of [event("miss","missed_call",undefined,"provider_verified",1),event("connected","callback_connected",undefined,"provider_verified",1),event("lead","qualified_lead",undefined,"provider_verified",.9),event("book","booking_created",15000,"provider_verified",.8),event("job","job_completed",undefined,"owner_reported",.8),event("inv","invoice_issued",12000),event("pay","payment_collected",12000,"financial_verified",.9),event("refund","refund_issued",2000),event("cost","cost_incurred",1000,"provider_verified",1)])await appendEvidence(s,e);const r=await new AttributionEngine(s).report("org","lead");assert.equal(r.bookedMinor,15000);assert.equal(r.netCollectedMinor,10000);assert.equal(r.confidenceWeightedMinor,8800);assert.equal(r.attributionClass,"direct_recovery");assert.equal(r.attributedMinor,8800);assert.equal(r.contributionMinor,7800);assert.equal(r.byStrength.providerVerifiedMinor,15000);assert.equal(r.byStrength.financialVerifiedMinor,24000);});
test("mixed currencies are rejected instead of silently converted",async()=>{const s=new MemoryAttributionStore();await appendEvidence(s,event("p","payment_collected",100));await appendEvidence(s,{...event("r","refund_issued",10),currency:"USD"});await assert.rejects(new AttributionEngine(s).report("org","lead"),/mixed_currency/);});
test("first and last acquisition touches remain ordered",async()=>{const s=new MemoryAttributionStore();await appendEvidence(s,event("lead","qualified_lead"));await addAcquisitionTouch(s,{id:"t2",organizationId:"org",leadId:"lead",channel:"agency",occurredAt:"2026-07-02T00:00:00Z"});await addAcquisitionTouch(s,{id:"t1",organizationId:"org",leadId:"lead",channel:"organic",occurredAt:"2026-07-01T00:00:00Z"});const r=await new AttributionEngine(s).report("org","lead");assert.equal(r.firstTouch.channel,"organic");assert.equal(r.lastTouch.channel,"agency");});
test("identity links reject cross-tenant merges and require audit actor for manual links",async()=>{const s=new MemoryAttributionStore();const link={id:"link",organizationId:"org",canonicalLeadId:"lead",linkedEntityType:"crm_contact",linkedEntityId:"crm1",matchMethod:"manual",confidence:.9,createdAt:t,actorId:"owner"};assert.equal(await linkIdentity(s,link,"org"),true);await assert.rejects(linkIdentity(s,{...link,id:"cross",organizationId:"other",linkedEntityId:"crm2"},"org"),/cross_tenant/);await assert.rejects(linkIdentity(s,{...link,id:"noactor",linkedEntityId:"crm3",actorId:undefined},"org"),/requires_actor/);});
test("partner access requires active assignment and scope, and revocation is immediate",async()=>{const s=new MemoryAttributionStore();await s.addPartner({id:"partner",name:"Agency",role:"agency",active:true,scopes:["reports.read"],createdAt:t});await assert.rejects(requirePartnerScope(s,"partner","org","reports.read"),/not_assigned/);await s.assignPartner({partnerId:"partner",organizationId:"org",state:"active",createdAt:t});await requirePartnerScope(s,"partner","org","reports.read");await assert.rejects(requirePartnerScope(s,"partner","org","accounts.manage"),/scope_denied/);await s.assignPartner({partnerId:"partner",organizationId:"org",state:"revoked",createdAt:t,revokedAt:t});await assert.rejects(requirePartnerScope(s,"partner","org","reports.read"),/not_assigned/);});
test("commission only accrues from high-confidence collected cash and is idempotent",async()=>{const s=new MemoryAttributionStore();await s.addPartner({id:"partner",name:"Agency",role:"agency",active:true,scopes:["commission.read"],createdAt:t});await s.assignPartner({partnerId:"partner",organizationId:"org",state:"active",createdAt:t});const payment=event("pay","payment_collected",10000,"financial_verified",.9);const a=await accrueCommission(s,"partner",payment,1000,t);const b=await accrueCommission(s,"partner",payment,1000,t);assert.equal(a.id,b.id);assert.equal(a.amountMinor,1000);assert.equal(a.ruleVersion,"commission-v1");await assert.rejects(accrueCommission(s,"partner",event("weak","payment_collected",10000,"financial_verified",.5),1000,t),/high_confidence/);});
test("pending commission reverses on refund evidence",async()=>{const s=new MemoryAttributionStore();await s.addPartner({id:"partner",name:"Agency",role:"agency",active:true,scopes:["commission.read"],createdAt:t});await s.assignPartner({partnerId:"partner",organizationId:"org",state:"active",createdAt:t});const c=await accrueCommission(s,"partner",event("pay","payment_collected",10000),1000,t);const r=await reverseCommission(s,"partner","pay","refund");assert.equal(r.state,"reversed");assert.equal(r.reversedByEventId,"refund");assert.equal(c.id,r.id);});
test("CRM outbox is idempotent, resumable, and delivery uses a stable key",async()=>{const s=new MemoryAttributionStore();const adapter={calls:[],failures:1,async send(input){this.calls.push(input);if(this.failures-- >0)throw new Error("rate limited");return{remoteId:"crm_1"};}};const sync=new CrmSyncService(s,adapter,()=>new Date(t));const item=await sync.enqueue("org","lead","hubspot","hash","lead-v2");await assert.rejects(sync.enqueue("org","lead","hubspot","hash","lead-v2"),/already_enqueued/);await assert.rejects(sync.deliver(item.id),/rate limited/);const sent=await sync.deliver(item.id);const again=await sync.deliver(item.id);assert.equal(sent.remoteId,again.remoteId);assert.equal(adapter.calls.length,2);assert.equal(adapter.calls[0].idempotencyKey,adapter.calls[1].idempotencyKey);assert.equal(adapter.calls[1].mappingVersion,"lead-v2");});
test("report exposes missing and conflicting evidence instead of inventing completion",async()=>{const s=new MemoryAttributionStore();await appendEvidence(s,event("book","booking_created",1000,"provider_verified",.8));await appendEvidence(s,event("won","owner_reported_won",undefined,"owner_reported",.6));await appendEvidence(s,event("lost","owner_reported_lost",undefined,"owner_reported",.6));const r=await new AttributionEngine(s).report("org","lead");assert.ok(r.missingEvidence.includes("qualified_lead"));assert.ok(r.missingEvidence.includes("job_completed"));assert.ok(r.missingEvidence.includes("acquisition_source"));assert.ok(r.conflicts.includes("conflicting_owner_outcome"));});
test("attribution replay is deterministic",async()=>{const s=new MemoryAttributionStore();await appendEvidence(s,event("lead","qualified_lead",undefined,"provider_verified",.9));await appendEvidence(s,event("book","booking_created",1000,"provider_verified",.8));const engine=new AttributionEngine(s,"recovery-v2");assert.deepEqual(await engine.report("org","lead"),await engine.report("org","lead"));});
test("cohort aggregation enforces privacy threshold and single currency",()=>{const base={organizationId:"a",leadId:"1",currency:"INR",bookedMinor:0,invoicedMinor:0,collectedMinor:100,refundedMinor:0,netCollectedMinor:100,confidenceWeightedMinor:90,attributedMinor:90,costMinor:10,contributionMinor:80,highestStrength:"financial_verified",attributionClass:"direct_recovery",attributionWeight:1,byStrength:{estimatedMinor:0,ownerReportedMinor:0,providerVerifiedMinor:0,financialVerifiedMinor:100},missingEvidence:[],conflicts:[],ruleVersion:"v1"};assert.throws(()=>aggregateCohort([base,{...base,organizationId:"b"}],3),/privacy_threshold/);const result=aggregateCohort([base,{...base,organizationId:"b",leadId:"2"},{...base,organizationId:"c",leadId:"3",missingEvidence:["job_completed"]}],3);assert.equal(result.organizationCount,3);assert.equal(result.missingOutcomeRate,1/3);});
test("Phase 5 migration enforces append-only evidence and server-mediated partner access",async()=>{const {readFile}=await import("node:fs/promises");const sql=await readFile("supabase/migrations/005_phase5_attribution_distribution.sql","utf8");assert.match(sql,/attribution_events_append_only/);assert.match(sql,/reject_append_only_mutation/);assert.match(sql,/unique \(organization_id, kind, source_type, source_id\)/);assert.match(sql,/revoke all on public\.partner_customer_assignments from anon,authenticated/);assert.match(sql,/protect_commission_evidence/);});
